package io.coral.contacts.model.enums

enum class StateEnum(var label:String) {
    Alabama("Alabama"),
    Alaska("Alaska"),
    Samoa("Samoa"),
    Arizona("Arizona"),
    Arkansas("Arkansas"),
    California("California"),
    Colorado("Colorado"),
    Connecticut("Connecticut"),
    Delaware("Delaware"),
    Columbia("Columbia"),
    Florida("Florida"),
    Georgia("Georgia"),
    Guam("Guam"),
    Hawaii("Hawaii"),
    Idaho("Idaho"),
    Illinois("Illinois"),
    Indiana("Indiana"),
    Iowa("Iowa"),
    Kansas("Kansas"),
    Kentucky("Kentucky"),
    Louisiana("Louisiana"),
    Maine("Louisiana"),
    Maryland("Maryland"),
    Massachusetts("Massachusetts"),
    Michigan("Michigan"),
    Minnesota("Minnesota"),
    Mississippi("Mississippi"),
    Missouri("Missouri"),
    Montana("Montana"),
    Nebraska("Nebraska"),
    Nevada("Nevada"),
    NewHampshire("New Hampshire"),
    NewJersey("New Jersey"),
    NewMexico("New Mexico"),
    NewYork("New York"),
    NorthCarolina("North Carolina"),
    NorthDakota("North Dakota"),
    Northern_Marianas_Islands("Northern Marianas Islands"),
    Ohio("Ohio"),
    Oklahoma("Oklahoma"),
    Oregon("Oregon"),
    Pennsylvania("Pennsylvania"),
    PuertoRico("PuertoRico"),
    RhodeIsland("RhodeIsland"),
    South_Carolina("South Carolina"),
    South_Dakota("South Dakota"),
    Tennessee("Tennessee"),
    Texas("Texas"),
    Utah("Utah"),
    Vermont("Vermont"),
    Virginia("Virginia"),
    Virgin_Islands("Virgin Islands"),
    Washington("Washington"),
    West_Virginia("West Virginia"),
    Wisconsin("Wisconsin"),
    Wyoming("Wyoming")
}